#!/usr/bin/env python3
"""Why every serialized host-control parameter gets a RANDOM handle. BACKLOG E81.

E81 measured the consequence -- ten loads of the identical bundled default rack
produce ten distinct documents -- and then said the cause was the thing to find
out: the parameters it measured *"carry `HostControl=` 14/21/22/40/49 and 9-10
digit random handles, so they are not taking the sequential branch at all, and
why not is the first thing to find out."*

THIS IS THE ANSWER, AND IT IS NOT A COLLISION. E56 fixed a collision -- the
sequential allocator iterated an `unordered_map` expecting sorted order, fell
through, and every request after the first landed in the random fallback. That
was a bug, and its fix holds. What is left is not a bug of that shape at all:

    PatchManager.cpp   CPatchManager::GetHostGeneratedParameter()
        uniqueIdDatabase.setHandleAutoGenerated(p, !stateful);

The second argument is `temporaryHandle`, and the branch it selects is the whole
question. `stateful` is a local of that function, set true in the per-host-control
switch above for exactly those host controls whose value is WRITTEN INTO THE
DOCUMENT. So `!stateful` routes every host control that serializes to the RANDOM
branch and every host control that does not to the SEQUENTIAL one.

That is precisely inverted with respect to the sequential branch's own stated
purpose. `UniqueSnowflake.cpp`, in the temporary branch:

    // This is useful for Host Controlled Parameters which get created during
    // project load. Using the same ID every time ensures resulting DSP XML is
    // consistant and comparable each run.

The parameters that reach the DSP XML are the stateful ones. They are the ones
excluded. So the comment describes the property E81 wants, on the branch that
cannot deliver it to anything that is saved.

WHAT THIS PROBE MEASURES, in two halves that are independent on purpose.

  SOURCE half (needs --syntheditlib, GATED and read-only here): parses the
  `HostControls` enum and walks `GetHostGeneratedParameter`'s switch, pairing
  each `stateful =` assignment with the `case HC_*` labels it falls under, and
  prints which branch each host control takes. Nothing is inferred from prose.

  DOCUMENT half (needs nothing but this repo): decodes every committed TiDE
  document and reports the `Handle=` actually carried by each host-control
  `<Parameter>`. A fixture is a `<Preset>` whose `<Param id="1">` holds the whole
  document base64'd, so this is one decode below the committed bytes -- the same
  reason `scripts/patch-cables.py` has to exist to read the cable lists.

THE CONTROL IS FREE AND NOBODY HAD SPENT IT. `HC_PROCESSOR_OFFLINE` (59) is in
the `stateful = false` group, and in the three documents that carry it, it carries
`Handle="0"` -- the smallest free key, which is what the sequential branch returns
-- while the five stateful host controls in the SAME documents carry 8-10 digit
randoms. Same document, same load, one predicate apart. So the branch is visible
in the committed bytes and does not have to be taken on the source's word.

And two INDEPENDENTLY saved documents disagree where two COPIES do not:
`e5-rack-macos-2026-08-21.xml` and `e53-vcv-rack-segv.xml` carry different
handles for the same five host controls, while `e53`/`e75`/`e83` -- which are
edits of one another rather than separate saves -- carry identical ones. That is
E81's ten-loads result, recoverable from the repo at zero cost.

    ./tests/e81_handle_branch_probe.py                      # document half only
    ./tests/e81_handle_branch_probe.py --syntheditlib ../SynthEditLib

Exit codes: 0 when the coupling is as described above, 1 when it has MOVED (which
is what makes this a regression guard for whichever way E81 is ruled), 2 when a
path or document cannot be read. **This probe describes TODAY's behaviour and is
therefore identical under every answer to E81's open question** -- it takes no
position on whether the handle SHOULD be deterministic, which is Jeff's ruling to
make and is filed as a `PROPOSED:` entry in docs/decisions.md.
"""

import argparse
import base64
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

# A handle at or above this is a draw from `random_generator() & 0x7fffffff`
# rather than a sequential key. The sequential branch returns the smallest free
# non-negative key, so in a document with a handful of host controls it returns
# single digits; the random branch has drawn 8-10 digits in every document
# measured. The gap is six orders of magnitude, so the threshold is not delicate.
RANDOM_HANDLE_FLOOR = 1_000_000

# Documents this repo commits. Prefabs and DefaultRack carry no host-control
# parameters at all -- they are containers, not presets -- which is a 'no
# observation', not a failure.
DOC_GLOBS = ('tests/fixtures/*.xml', 'tests/fixtures/*.synthedit',
             'DefaultRack.synthedit', 'RackModules/*.synthedit')


def repo_root():
    return pathlib.Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------- source half

def strip_comments(src):
    """Blank out // and /* */ comments, PRESERVING line numbers and newlines.

    Not cosmetic. `PatchManager.cpp` carries a commented-out
    `//	case HC_MAX_LATENCY_COMPENSATION:` immediately above a live case group,
    and matching it attributes that group's `stateful` to a host control which
    does not exist in the enum at all -- it is not in `HostControls.h`. A probe
    that reports a disabled line as live is the defect this lane keeps finding in
    prose (a citation inside an `#if 0`, a count of 23 that measures 15), and it
    is not worth reproducing in a script whose whole point is to replace reading
    with measuring.
    """
    out, i, n = [], 0, len(src)
    while i < n:
        c = src[i]
        if c == '/' and i + 1 < n and src[i + 1] == '/':
            while i < n and src[i] != '\n':
                out.append(' ')
                i += 1
        elif c == '/' and i + 1 < n and src[i + 1] == '*':
            out.append('  ')
            i += 2
            while i < n and not (src[i] == '*' and i + 1 < n and src[i + 1] == '/'):
                out.append('\n' if src[i] == '\n' else ' ')
                i += 1
            out.append('  ')
            i += 2
        elif c in '"\'':
            quote = c
            out.append(c)
            i += 1
            while i < n and src[i] != quote:
                if src[i] == '\\' and i + 1 < n:
                    out.append(src[i])
                    i += 1
                out.append(src[i])
                i += 1
            if i < n:
                out.append(src[i])
                i += 1
        else:
            out.append(c)
            i += 1
    return ''.join(out)


def parse_host_controls(selib):
    """HostControls.h -> {value: name}. Counted from the enum, never guessed."""
    src = (selib / 'HostControls.h').read_text(encoding='utf-8', errors='replace')
    m = re.search(r'enum HostControls\s*\{(.*?)\}', src, re.S)
    if not m:
        raise ValueError('no `enum HostControls` in HostControls.h')
    body = re.sub(r'//[^\n]*', '', re.sub(r'/\*.*?\*/', '', m.group(1), flags=re.S))
    table, val = {}, 0
    for tok in body.split(','):
        tok = tok.strip()
        if not tok:
            continue
        if '=' in tok:
            name, v = tok.split('=', 1)
            name, val = name.strip(), int(v.strip(), 0)
        else:
            name = tok
        table[val] = name
        val += 1
    return table


def parse_stateful_switch(selib):
    """GetHostGeneratedParameter -> {HC_NAME: bool stateful}.

    Walks the function body pairing each `stateful =` assignment with the run of
    `case HC_*:` labels it sits under. Fall-through groups (several labels, one
    body) are handled by accumulating labels until a non-case statement starts.
    """
    path = selib / 'EditorLib' / 'PatchManager.cpp'
    lines = strip_comments(path.read_text(encoding='utf-8', errors='replace')).split('\n')

    start = end = None
    for i, ln in enumerate(lines):
        if start is None and 'CPatchManager::GetHostGeneratedParameter' in ln \
                and not ln.lstrip().startswith('//'):
            start = i
        elif start is not None and re.match(r'^\}', ln):
            end = i
            break
    if start is None:
        raise ValueError('GetHostGeneratedParameter not found in PatchManager.cpp')
    end = end if end is not None else len(lines)

    out, group, collecting, call_line = {}, [], False, None
    for i in range(start, end):
        n, ln = i + 1, lines[i]
        cases = re.findall(r'case\s+(HC_[A-Z0-9_]+)\s*:', ln)
        if cases:
            if not collecting:
                group, collecting = [], True
            group += cases
            continue
        if ln.strip() and collecting:
            collecting = False
        m = re.search(r'\bstateful\s*=\s*(true|false)\b', ln)
        if m and 'bool stateful' not in ln:
            for hc in group:
                out[hc] = (m.group(1) == 'true', n)
        if 'setHandleAutoGenerated' in ln:
            call_line = (n, ln.strip())
    return out, (start + 1, end), call_line


# -------------------------------------------------------------- document half

def decode_document(path):
    """A fixture is a <Preset> whose <Param id="1"> holds the base64'd document.
    A bare .synthedit is already the document."""
    raw = path.read_bytes()
    head = raw.lstrip()[:400]
    if head.startswith(b'<?xml') and b'<Preset' in head:
        root = ET.fromstring(raw.decode('utf-8', errors='replace'))
        for p in root.iter():
            if p.tag.lower() in ('param', 'parameter') and p.get('id') == '1':
                val = p.get('val')
                if val:
                    return base64.b64decode(val)
    return raw


def host_control_handles(doc):
    """[(hostControl, handle_or_None)] for every <Parameter HostControl=...>."""
    found = []
    for m in re.finditer(rb'<Parameter\b[^>]*>', doc):
        tag = m.group(0)
        hc = re.search(rb'HostControl="(\d+)"', tag)
        if not hc:
            continue
        hnd = re.search(rb'Handle="(-?\d+)"', tag)
        found.append((int(hc.group(1)),
                      int(hnd.group(1)) if hnd else None))
    return sorted(found)


# ------------------------------------------------------------------- reporting

def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--syntheditlib',
                    help='SynthEditLib checkout (read-only; enables the source half)')
    args = ap.parse_args()

    root = repo_root()
    print('E81 -- which handle branch a host-control parameter takes, and why\n')

    names, stateful = {}, {}
    if args.syntheditlib:
        selib = pathlib.Path(args.syntheditlib).expanduser()
        if not selib.is_dir():
            print(f'SynthEditLib path is not a directory: {selib}', file=sys.stderr)
            return 2
        try:
            names = parse_host_controls(selib)
            stateful, span, call = parse_stateful_switch(selib)
        except (OSError, ValueError) as exc:
            print(f'cannot read SynthEditLib sources: {exc}', file=sys.stderr)
            return 2

        print(f'SOURCE  {selib}')
        print(f'  GetHostGeneratedParameter spans lines {span[0]}..{span[1]} '
              f'of EditorLib/PatchManager.cpp')
        if call:
            print(f'  {call[0]}: {call[1]}')
        print(f'  HostControls.h declares {len(names)} host controls; '
              f'{len(stateful)} of them assign `stateful` explicitly\n')

        by_val = {v: k for k, v in names.items()}
        unknown = [hc for hc in stateful if hc not in by_val]
        print(f'  {"HC":>3s}  {"name":38s} {"stateful":8s} {"handle branch":14s} line')
        for hc in sorted(stateful, key=lambda h: by_val.get(h, 9999)):
            st, ln = stateful[hc]
            val = by_val.get(hc)
            print(f'  {("?" if val is None else str(val)):>3s}  {hc:38s} {str(st):8s} '
                  f'{"RANDOM" if st else "sequential":14s} {ln}')
        print()
        if unknown:
            # A case label naming a host control the enum does not declare means
            # this probe's model of the switch has drifted -- most likely it has
            # matched a disabled line. Say so rather than printing a value.
            print('  ! case label(s) not declared in HostControls.h: '
                  + ', '.join(sorted(unknown)))
            print('  ! the switch walk has drifted; do not trust the table above')
            return 1

    print('DOCUMENT  every committed TiDE document, one decode below the bytes\n')
    docs = []
    for g in DOC_GLOBS:
        docs += sorted(root.glob(g))
    if not docs:
        print('no committed documents found', file=sys.stderr)
        return 2

    observed = {}          # hostControl -> set of handles seen
    rows = []
    for d in docs:
        try:
            doc = decode_document(d)
        except Exception as exc:                       # noqa: BLE001 - report, not raise
            print(f'  cannot decode {d.relative_to(root)}: {exc}', file=sys.stderr)
            return 2
        hcs = host_control_handles(doc)
        rows.append((d.relative_to(root), hcs))
        for hc, h in hcs:
            observed.setdefault(hc, set()).add(h)

    for rel, hcs in rows:
        if not hcs:
            print(f'  {str(rel):46s}  no host-control parameters')
            continue
        desc = ', '.join(f'HC{hc}:{h}' for hc, h in hcs)
        print(f'  {str(rel):46s}  {desc}')
    print()

    # ------------------------------------------------------------- the coupling
    failures = []
    print('COUPLING  a serialized host control carries a random handle; a '
          'non-serialized one carries a sequential key\n')
    for hc in sorted(observed):
        handles = sorted(x for x in observed[hc] if x is not None)
        if not handles:
            continue
        looks_random = all(h >= RANDOM_HANDLE_FLOOR for h in handles)
        looks_seq = all(h < RANDOM_HANDLE_FLOOR for h in handles)
        name = names.get(hc, '?')
        verdict = 'RANDOM' if looks_random else ('sequential' if looks_seq else 'MIXED')
        distinct = len(set(handles))
        print(f'  HC{hc:<3d} {name:38s} {verdict:11s} '
              f'{distinct} distinct value(s) across {len(handles)} document(s)')

        if stateful and name in stateful:
            st, _ = stateful[name]
            expected = 'RANDOM' if st else 'sequential'
            if verdict != expected:
                failures.append(
                    f'HC{hc} ({name}) is stateful={st}, so the source says '
                    f'{expected}, but the documents carry {verdict}')

    print()
    if stateful:
        if failures:
            print('THE COUPLING HAS MOVED:')
            for f in failures:
                print(f'  ! {f}')
            print('\nE81 was filed against the behaviour above. Re-read the row '
                  'before trusting it.')
            return 1
        print('The source half and the document half agree. This is E81 as filed:')
        print('  a host control is given a random handle BECAUSE it is the kind '
              'that gets saved.')
    else:
        print('Document half only. Pass --syntheditlib to check this against the '
              'branch the source actually selects.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
